[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs

lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
  adafruit/Adafruit ADS1X15
  https://github.com/asukiaaa/MPU9250_asukiaaa.git
  stm32duino/STM32duino VL53L4CD

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=0